Repository jenkinsci/external-monitor-job-plugin, pull requests merged in 2022-09, with the labels that each got.

#53 bump parent pom from 4.33 to 4.47
  pom.xml
  src/main/resources/index.jelly
Labels: developer

#41 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#27 Fix/fix typo in readme
  .gitignore
  README.md
Labels: documentation

#46 Delete newJobDetail.jelly
  src/main/resources/hudson/model/ExternalJob/newJobDetail.jelly
Labels: chore
