Repository jenkinsci/external-monitor-job-plugin, pull requests merged in 2022-01, with the labels that each got.

#20 Update parent POM and jenkins baseline for JDK11 compatibility
  pom.xml
Labels: dependencies

#19 Use GitHub as the source of documentation
  CHANGELOG.md
  README.md
  pom.xml
Labels: documentation

#22 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#26 Prepare for sunset icon removal from core
  src/main/resources/hudson/model/ExternalJob/sidepanel.jelly
  src/main/resources/hudson/model/ExternalRun/sidepanel.jelly
Labels: bug
